name: MUDTapper
options:
  bundleIdPrefix: com.mudtapper
  deploymentTarget:
    iOS: "15.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true
  generateEmptyDirectories: true

settings:
  SWIFT_VERSION: "5.9"
  IPHONEOS_DEPLOYMENT_TARGET: "15.0"
  TARGETED_DEVICE_FAMILY: "1,2"
  SUPPORTS_MACCATALYST: false

targets:
  MUDTapper:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    
    sources:
      - path: MUDTapper
        excludes:
          - "**/*.md"
          - "**/README*"
          - "**/project.yml"
          - "**/Info.plist"
    
    info:
      path: MUDTapper/Info.plist
      properties:
        CFBundleDisplayName: MUDTapper
        CFBundleIdentifier: com.mudtapper.MUDTapper
        CFBundleName: MUDTapper
        CFBundleShortVersionString: "2.0.0"
        CFBundleVersion: "1"
        LSRequiresIPhoneOS: true
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
        UIApplicationSupportsIndirectInputEvents: true
        UILaunchStoryboardName: LaunchScreen
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIAppFonts:
          - "SourceCodePro-Regular.ttf"
          - "SourceCodePro-Bold.ttf"
        CFBundleURLTypes:
          - CFBundleURLName: "Telnet URL"
            CFBundleURLSchemes:
              - "telnet"
    
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.mudtapper.MUDTapper
      INFOPLIST_FILE: MUDTapper/Info.plist
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
      DEVELOPMENT_TEAM: ""
      CODE_SIGN_STYLE: Automatic
      SWIFT_VERSION: "5.9"
      IPHONEOS_DEPLOYMENT_TARGET: "15.0"
      TARGETED_DEVICE_FAMILY: "1,2"
      SUPPORTS_MACCATALYST: false 